[staging]
Staging ansible_host=172.31.31.181 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/buildkey.pem ansible_ssh_common_args-'-o StrictHostKeyChecking=no'
[Production]
Production ansible_host=172.31.22.37 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/buildkey.pem ansible_ssh_common_args-'-o StrictHostKeyChecking=no'
